---
- hosts: dc1
  become: true

  roles:
  - opdk-setup-selinux-disable
  - opdk-dns-resolver
  - opdk-shutdown-iptables
  - opdk-time-sync
  - opdk-setup-hostfile
  - opdk-setup-os
  - opdk-setup-os-dev-validation
  - opdk-setup-installer
  - opdk-setup-aio
  - opdk-setup-org
  - opdk-setup-logs-configs
  - opdk-setup-status