---
# tasks file for opdk-setup-status

- name: Collect All Status
  shell: "{{ all_status }}"
  register: results
  ignore_errors: yes
  when: opdk_version == '4.15.07.03'

- name: Collect All Status
  shell: "{{ apigee_all }} status"
  register: results
  ignore_errors: yes
  when: opdk_version == '4.16.01' or opdk_version == '4.16.05'

- name: View All Status Results
  debug:
    var: results
