---
- include: common_integrated_facts.yml

- include: aws_integrated_facts.yml

- include: '4150703-main.yml'
  when: opdk_version | version_compare('4.16.01', '<')

- name: Apigee 4.16.01 or greater DS installation
  shell: '{{ apigee_setup }} -p ds -f {{ opdk_installation_config_file }}'
  when: opdk_version | version_compare('4.16.01', '>=')
