---
- include: common_integrated_facts.yml

- include: aws_integrated_facts.yml

- include: '4150703-main.yml'
  when: opdk_version == '4.15.07.03'

- include: '4160100-main.yml'
  when: opdk_version == '4.16.01'

- include: '4160500-main.yml'
  when: opdk_version == '4.16.05'
