---
- include: common_integrated_facts.yml

- include: aws_integrated_facts.yml

- include: '4150703-main.yml'
  when: opdk_version == '4.15.07.03'

- name: Apigee DS installation
  shell: '{{ apigee_setup }} -p ds -f {{ opdk_response_file_path }}'
  when: opdk_version == '4.16.01'

- name: Apigee DS installation
  shell: '{{ apigee_setup }} -p ds -f {{ opdk_response_file_path }}'
  async: 5
  poll: 0
  when: opdk_version == '4.16.05'
