---
#--------------------------------
# Baas Default Variables, this section could be a candidate for
# export into another role just for Baas defaults.

# Organization name used in Edge and Baas setups
org_name: aws-tmobile-baas

# Define the API BaaS administrator account.
baas_admin_name: 'baas_admin'
baas_admin_email: ApigeeAdmin@T-Mobile.com
baas_admin_pass: '123@T-Mobile'
baas_superuser_name: 'superuser'
baas_superuser_pass: '987@T-Mobile'

# Cassandra uname/pword if you enabled Cassandra authentication.
# Even if you have not enabled Cassandra authentication,
# you must pass values for these properties.
opdk_cass_username: 'cassandra'
# Default value
opdk_cass_password: 'cassandra'

# API BaaS Stack information.
# Default cluster name is "apigee_baas"
baas_cluster_name: 'tmobile_baas'

# URL and port of the load balancer for the API BaaS Stack nodes,
# or IP/DNS and port of a single Stack node with no load balancer.
baas_load_balancer_host: 'internal-rbl-Apigee-elbBaaS-J308EOVMI0A2-141988222.us-west-2.elb.amazonaws.com'
baas_load_balancer_port: '8080'

# Portal port. Default value is 9000.
baas_portal_port: '9000'

# SMTP information. BaaS requires an SMTP server.
baas_smtp_host: 'mail.t-mobile.com'
baas_smtp_port: '25'
baas_smtp_user: ''
baas_smtp_user_pass: ''
baas_smtp_ssl: 'n'