---
# tasks file for opdk-setup-rollback-os

- name: Clean up other JDKs
  shell: 'rpm -e $(rpm -qa | egrep "^(java|jdk|jre).*")'
  ignore_errors: yes

- name: remove yum epel repository
  yum:
    name: "{{ item }}"
    state: absent
  with_items:
    - epel-release
  when: ansible_distribution | lower == "centos"

- name: remove yum centos-release-SCL repository
  yum:
    name: "{{ item }}"
    state: absent
  with_items:
    - centos-release-SCL
  when: ansible_distribution_major_version == "6" and ansible_distribution | lower == "centos"

- name: remove yum epel repository for Oracle Linux 7
  yum:
    name: "{{ item }}"
    state: absent
  with_items:
  - 'https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm'
  when: ansible_distribution_major_version == "7"

- name: remove yum epel repository for Oracle Linux 6
  yum:
    name: "{{ item }}"
    state: absent
  with_items:
  - 'https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm'
  when: ansible_distribution_major_version == "6" and ansible_distribution | lower == "oraclelinux"

- name: Clear all artifacts from YUM repo
  shell: 'yum clean all'
  ignore_errors: yes

- block:
  - name: Remove the apigee user
    ignore_errors: yes
    user:
      name: "{{ opdk_user_name }}"
      state: absent
      remove: yes
    delay: 10
    async: 10
    poll: 0

  - name: Remove the apigee group
    ignore_errors: yes
    group:
      name: "{{ opdk_group_name }}"
      state: absent
    delay: 10
    async: 10
    poll: 0

  rescue:

  - name: Release any apigee user owned processes
    shell: 'killall5 -9 -u apigee'
    ignore_errors: yes
    delay: 10
    async: 10
    poll: 0

  - name: Remove the apigee user
    ignore_errors: yes
    user:
      name: "{{ opdk_user_name }}"
      state: absent
      remove: yes
    delay: 10
    async: 10
    poll: 0

  - name: Remove the apigee group
    ignore_errors: yes
    group:
      name: "{{ opdk_group_name }}"
      state: absent
    delay: 10
    async: 10
    poll: 0
#
#- name: Restart the node
#  ignore_errors: yes
#  shell: 'reboot now'
#  delay: 10
#  async: 10
#  poll: 0
