---
# tasks file for opdk-setup-rollback-os

- name: Clean up other JDKs
  yum:
    name: '{{ item }}'
    state: absent
  with_items:
  - java*
  - jdk*
  - jre*

- name: remove yum centos-release-SCL repository
  yum:
    name: "{{ item }}"
    state: absent
  with_items:
    - centos-release-SCL
  when: ansible_distribution_major_version == "6" and ansible_distribution | lower == "centos"

- name: Clear all artifacts from YUM repo
  shell: 'yum clean all'
  ignore_errors: yes

- name: Determine current user
  shell: whoami
  register: whoami

- name: Determine if safe to kill user owned process
  set_fact:
    kill_user: whoami.stdout != '{{ opdk_user_name }}'

- name: Release any apigee user owned processes
  shell: 'pkill -u {{ opdk_user_name }}'
  ignore_errors: yes
  when: kill_user

- name: Remove the apigee user
  ignore_errors: yes
  user:
    name: "{{ opdk_user_name }}"
    state: absent
    remove: yes
  delay: 10
  async: 10
  poll: 0

- name: Remove the apigee group
  ignore_errors: yes
  group:
    name: "{{ opdk_group_name }}"
    state: absent
  delay: 10
  async: 10
  poll: 0
