---
# tasks file for opdk-setup-selinux-disable
- name: Permanently disable SELINUX
  lineinfile:
    dest: /etc/selinux/config
    regexp: "^(SELINUX=)"
    line: '\1disabled'
    backrefs: yes
    backup: yes

- name: Temporarily disable selinux on CentOS 7
  ignore_errors: true
  shell: setenforce 0
  when: ansible_os_family | lower == 'redhat' and ansible_distribution_major_version == "7"

