---
# tasks file for opdk-setup-selinux-disable
- name: Permanently disable SELINUX
  lineinfile:
    dest: /etc/selinux/config
    regexp: "^(SELINUX=)"
    line: '\1disabled'
    backrefs: yes
    backup: yes

- name: Obtain status of selinux
  shell: sestatus
  register: status

- name: Temporarily disable selinux on redhat OS families version 7
  shell: setenforce 0
  when: "ansible_os_family | lower == 'redhat' and ansible_distribution_major_version == '7' and 'enabled' in status.stdout"

- name: Refresh setup facts
  setup:

- name: Fail playbook if selinux is running
  fail:
    msg: 'SELinux MUST be disabled, selinux has been updated, please restart the node.'
  when: "{{ ansible_selinux.status | lower != 'disabled' }}"
