---
- hosts: qpid
  vars_files:
  - opdk-setup-settings.yml
  roles:
  - opdk-setup-qpid
  tags:
  - qpid

- hosts: pgmaster
  serial: 1
  vars_files:
  - opdk-setup-settings.yml
  roles:
  - opdk-setup-postgres
  - opdk-setup-postgres-master
  tags:
  - pg

- hosts: pgstandby
  serial: 1
  vars_files:
  - opdk-setup-settings.yml
  roles:
  - opdk-setup-postgres
  - opdk-setup-postgres-standby
  tags:
  - pg
