---
# tasks file for opdk-setup-default-settings
- name: Update setup facts
  setup:

- name: Update AWS facts, if running AWS
  ec2_facts:
  when: ansible_bios_version | search('amazon')

- include: network-interface-name.yml

- name: Get public address for node
  set_fact:
    public_address: '{{ inventory_hostname }}'

- name: Get private address for node
  set_fact:
    local_address: '{{ hostvars[inventory_hostname][interface_name].ipv4.address }}'

- name: Get public address for node on AWS
  set_fact:
    public_address: '{{ ansible_ec2_public_ipv4 }}'
  when: "{{ ansible_bios_version | search('amazon') and ansible_ec2_public_ipv4 is defined}}"

- name: Get private address for node on AWS
  set_fact:
    local_address: '{{ ansible_ec2_local_ipv4 }}'
  when: "{{ ansible_bios_version | search('amazon') and ansible_ec2_local_ipv4 is defined }}"

- name: Get local management server if on dc-1
  set_fact:
    local_mgmt_ip: "{{ hostvars[groups['dc-1-ms'][0]][interface_name].ipv4.address }}"
  when: groups['dc-1'] is defined and inventory_hostname in groups['dc-1']

- name: Get local management server if on dc-2
  set_fact:
    local_mgmt_ip: "{{ hostvars[groups['dc-2-ms'][0]][interface_name].ipv4.address }}"
  when: groups['dc-2'] is defined and inventory_hostname in groups['dc-2']

- name: Get local management server if on dc-1
  set_fact:
    public_mgmt_ip: "{{ groups['dc-1-ms'][0] }}"
  when: groups['dc-1'] is defined and inventory_hostname in groups['dc-1']

- name: Get local management server if on dc-2
  set_fact:
    public_mgmt_ip: "{{ groups['dc-2-ms'][0] }}"
  when: groups['dc-2'] is defined and inventory_hostname in groups['dc-2']

- name: Cache public address for node
  cache:
    key: 'public_address'
    value: '{{ inventory_hostname }}'

- name: Cache local address for node
  cache:
    key: 'local_address'
    value: '{{ local_address }}'

- name: Cache public mgmt address for node
  cache:
    key: 'public_mgmt_ip'
    value: '{{ public_mgmt_ip }}'

- name: Cache local mgmt address for node
  cache:
    key: 'local_mgmt_ip'
    value: '{{ local_mgmt_ip }}'

- name: Cache interface name for node
  cache:
    key: 'interface_name'
    value: '{{ interface_name }}'


