---
# tasks file for apigee-startup

- include: 4150703-main.yml
  when: opdk_version | version_compare('4.16.01', '<')

- name: Start Apigee
  shell: '{{ apigee_all }} start'
  register: start_cmd_report
  when: opdk_version | version_compare('4.16.01', '>=')

