---
- hosts: dc1
  become: true
  vars:
    graphite_host: "{{ hostvars[ansible_hostname]['groups']['monitor'][0] }}"

  roles:
  - opdk-setup-collectd

- hosts: monitor
  become: true

  roles:
  - opdk-setup-graphite
  - opdk-setup-grafana
  - opdk-setup-status
