---
# tasks file for opdk-setup-rmp

- include: 4150703-main.yml
  when: opdk_version | version_compare('4.16.01', '<')

- name: Router and Message Processor installation
  shell: '{{ apigee_setup }} -p rmp -f {{ opdk_installation_config_file }}'
  when: opdk_version | version_compare('4.16.01', '>=')
