---
# tasks file for opdk-setup-logs
- name: Find config files to download
  shell: "find {{ item.dir }} -type f -name '{{ item.name }}'"
  register: logs
  with_items:
  - { dir: '/tmp', name: '*conf' }
  - { dir: '{{ apigee_installation_home }}/customer', name: '*' }
  - { dir: '{{ apigee_installation_home }}/token/', name: '*conf' }
  - { dir: '{{ apigee_installation_home }}/*message-processor/', name: '*conf' }
  - { dir: '{{ apigee_installation_home }}/*router/', name: '*conf' }
  - { dir: '{{ apigee_installation_home }}/*postgresql/', name: '*conf' }
  - { dir: '{{ apigee_installation_home }}/*postgres-server/', name: '*conf' }
  - { dir: '{{ apigee_installation_home }}/*cassandra/', name: '*conf' }
  - { dir: '{{ apigee_installation_home }}/*qpid-server/', name: '*conf' }
  - { dir: '{{ apigee_installation_home }}/*qpidd/', name: '*conf' }
  - { dir: '{{ apigee_installation_home }}/*zookeeper/', name: '*conf' }
  - { dir: '{{ apigee_installation_home }}', name: '*yaml' }
  - { dir: '{{ apigee_installation_home }}', name: '*sh' }
  ignore_errors: yes

- name: Download config files
  fetch:
    src: "{{ item }}"
    dest: '{{ conf_logs_dir }}'
  with_items: '{{ logs.results[0].stdout_lines }}'
  ignore_errors: yes

- name: Download config files
  fetch:
    src: "{{ item }}"
    dest: '{{ conf_logs_dir }}'
  with_items: '{{ logs.results[1].stdout_lines }}'
  ignore_errors: yes

- name: Download config files
  fetch:
    src: "{{ item }}"
    dest: '{{ conf_logs_dir }}'
  with_items: '{{ logs.results[2].stdout_lines }}'
  ignore_errors: yes

- name: Download config files
  fetch:
    src: "{{ item }}"
    dest: '{{ conf_logs_dir }}'
  with_items: '{{ logs.results[3].stdout_lines }}'
  ignore_errors: yes

- name: Download config files
  fetch:
    src: "{{ item }}"
    dest: '{{ conf_logs_dir }}'
  with_items: '{{ logs.results[4].stdout_lines }}'
  ignore_errors: yes

- name: Download config files
  fetch:
    src: "{{ item }}"
    dest: '{{ conf_logs_dir }}'
  with_items: '{{ logs.results[5].stdout_lines }}'
  ignore_errors: yes

- name: Download config files
  fetch:
    src: "{{ item }}"
    dest: '{{ conf_logs_dir }}'
  with_items: '{{ logs.results[6].stdout_lines }}'
  ignore_errors: yes

- name: Download config files
  fetch:
    src: "{{ item }}"
    dest: '{{ conf_logs_dir }}'
  with_items: '{{ logs.results[7].stdout_lines }}'
  ignore_errors: yes

- name: Download config files
  fetch:
    src: "{{ item }}"
    dest: '{{ conf_logs_dir }}'
  with_items: '{{ logs.results[8].stdout_lines }}'
  ignore_errors: yes

- name: Download config files
  fetch:
    src: "{{ item }}"
    dest: '{{ conf_logs_dir }}'
  with_items: '{{ logs.results[9].stdout_lines }}'
  ignore_errors: yes

- name: Download config files
  fetch:
    src: "{{ item }}"
    dest: '{{ conf_logs_dir }}'
  with_items: '{{ logs.results[10].stdout_lines }}'
  ignore_errors: yes

- name: Download config files
  fetch:
    src: "{{ item }}"
    dest: '{{ conf_logs_dir }}'
  with_items: '{{ logs.results[11].stdout_lines }}'
  ignore_errors: yes


