---
#- include: prep_os/update-user.yml
#  vars:
#    hosts: 'planet'
#    user: 'root'

- include: prep_os/facts.yml

- include: prep_os/opdk-setup-os.yml

- include: prep_os/opdk-setup-openjdk.yml
  vars:
    hosts: 'dc-1'

- include: prep_bootstrap/opdk-setup-bootstrap.yml
  vars:
    hosts: 'dc-1-ms'
  when: create_archive is defined and create_archive

- include: prep_bootstrap/opdk-setup-bootstrap-archive-create-download.yml
  vars:
    hosts: 'ms'
  when: create_archive is defined and create_archive

- include: prep_bootstrap/opdk-setup-bootstrap-rollback.yml
  vars:
    hosts: 'dc-1-ms'
  when: create_archive is defined and create_archive

- include: prep_os/opdk-setup-os.yml
  when: create_archive is defined and create_archive

- include: prep_os/opdk-setup-openjdk.yml
  vars:
    hosts: 'dc-1-ms'
  when: create_archive is defined and create_archive

- include: prep_bootstrap/opdk-setup-bootstrap-archive.yml
  vars:
    hosts: 'dc-1'
  when: (existing_archive is defined and existing_archive) or (create_archive is defined and create_archive)

- include: prep_bootstrap/opdk-setup-bootstrap.yml
  vars:
    hosts: 'dc-1'
  when: create_archive is not defined or not create_archive

- include: component_installations/opdk-setup-component-installer.yml
  vars:
    hosts: 'dc-1'

- include: component_installations/opdk-setup-ds.yml
  vars:
    hosts: 'dc-1-ds'

- include: component_installations/opdk-setup-ms.yml
  vars:
    hosts: 'dc-1-ms'

- include: component_installations/opdk-setup-rmp.yml
  vars:
    hosts: 'dc-1-rmp'

- include: component_installations/opdk-setup-qpid.yml
  vars:
    hosts: 'dc-1-qpid'

- include: component_installations/opdk-setup-postgres-master.yml
  vars:
    hosts: 'dc-1-pgmaster'

- include: component_installations/opdk-setup-postgres-standby.yml
  vars:
    hosts: 'dc-1-pgstandby'

- include: validation/opdk-setup-startup.yml

- include: validation/opdk-setup-validate.yml

- include: validation/opdk-setup-org.yml
  vars:
    hosts: 'dc-1-ms[0]'

- include: validation/opdk-setup-status.yml
  vars:
    hosts: 'dc-1'

- include: validation/opdk-setup-log-files.yml
