---
- include: facts.yml

- hosts: planet
  roles:
#  - opdk-setup-apigee-log-files
  - { role: fetch-files, fetch_files: '{{ apigee_log_files }}' }

  tags:
  - logs
  - apigee-logs

- hosts: planet
  become: true
  strategy: free
  roles:
  - { role: fetch-files, fetch_files: '{{ system_config_files }}' }
#  - opdk-setup-system-configs-logs
  tags:
  - os
  - os-logs
  - logs


- hosts: planet
  roles:
  - { role: fetch-files, fetch_files: '{{ apigee_config_files }}' }
#  - opdk-setup-apigee-config-files
  - opdk-setup-system-configs-logs
  tags:
  - configs
  - logs


- hosts: planet
  roles:
  - { role: fetch-files, fetch_files: '{{ apigee_property_files }}' }
  tags:
  - properties
  - apigee-properties
  - logs
