---
- hosts: pgmaster
  serial: 1
  vars:
    target_host_name: "{{ hostvars[inventory_hostname]['groups']['pgstandby'][0] }}"
  roles:
  - opdk-setup-ssh

- hosts: pgstandby
  serial: 1
  vars:
    target_host_name: "{{ hostvars[inventory_hostname]['groups']['pgmaster'][0] }}"
  roles:
  - opdk-setup-ssh
