---

- include: facts.yml

- include: opdk-setup-os.yml

- include: opdk-setup-openjdk.yml
  vars:
    hosts: 'dc-2'

- include: opdk-setup-bootstrap-archive.yml
  vars:
    hosts: 'dc-2'
  when: existing_archive is defined and existing_archive

- include: opdk-setup-bootstrap-create-download.yml
  vars:
    hosts: 'dc-2-ms'
  when: create_archive is defined and create_archive

- include: opdk-setup-bootstrap.yml
  vars:
    hosts: 'dc-2'
  when: create_archive is not defined or not create_archive

- include: opdk-setup-component-installer.yml
  vars:
    hosts: 'planet'

- include: opdk-setup-ds.yml
  vars:
    hosts: 'dc-2-ds'

- include: opdk-setup-ds.yml
  vars:
    hosts: 'dc-1-ds'

- include: opdk-cassandra-client-update.yml
  vars:
     hosts: 'dc-1-ms'

- include: opdk-setup-ms.yml
  vars:
    hosts: 'dc-1-ms'

- include: opdk-cassandra-rebuild.yml
  vars:
    hosts: 'dc-2-ds'

- include: opdk-setup-ms.yml
  vars:
    hosts: 'dc-2-ms'
  tags:
  - ms2

- include: opdk-setup-rmp.yml
  vars:
    hosts: 'dc-2-rmp'

- include: opdk-setup-rmp.yml
  vars:
    hosts: 'dc-1-rmp'

- include: opdk-setup-qpid.yml
  vars:
    hosts: 'dc-2-qpid'

- include: opdk-setup-postgres-master.yml
  vars:
    hosts: 'dc-2-pgmaster'

- include: opdk-setup-postgres-standby.yml
  vars:
    hosts: 'dc-2-pgstandby'

- include: opdk-setup-startup.yml

- include: opdk-setup-validate.yml

- include: opdk-setup-status.yml
  vars:
    hosts: 'planet'

- include: opdk-setup-log-files.yml
