---
- include: facts.yml

- hosts: planet
  roles:
  - { role: fetch-files, fetch_files: '{{ apigee_config_files }}' }
#  - opdk-setup-apigee-config-files
  - opdk-setup-system-configs-logs
  tags:
  - configs
  - logs
