---
# tasks file for opdk-setup-ssh

- include: common_integrated_facts.yml

- include: aws_integrated_facts.yml

#- name: Setup hostvars name
#  set_fact:
#    hostvarname: '{{ public_address }}'

- name: target_host_name
  debug:
    var: target_host_name

- name: Update authorized_keys
  become_user: "{{ opdk_user_name }}"
  authorized_key:
    user: "{{ opdk_user_name }}"
    key: "{{ lookup('file', 'ssh_keys/ssh_pub_key_{{ target_host_name }}.pub') }}"

- name: known_hosts prep
  set_fact:
    known_hosts_prep: "{{ lookup('file', 'ssh_keys/known_hosts_prep_{{ target_host_name }}.txt') }}"

- name: set fact to generate known_hosts
  set_fact:
    generate_known_hosts: "ssh-keyscan {{ known_hosts_prep }}"

- name: Generate known_hosts
  shell: "{{ generate_known_hosts }}"
  register: known_hosts_content

- name: Generate known hosts content
  debug:
    var: known_hosts_content

- name: Update known_hosts
  become_user: "{{ opdk_user_name }}"
  known_hosts:
    path: /home/{{ opdk_user_name }}/.ssh/known_hosts
    key: "{{ known_hosts_content.stdout }}"
    name: "{{ known_hosts_prep }}"
    state: present
