---
# tasks file for opdk-setup-logs
- name: Find installation property files to download
  shell: "find {{ item.dir }} -type f -name '{{ item.name }}'"
  register: logs
  with_items: '{{ property_files }}'
  ignore_errors: yes

- name: Pull results out of property search
  set_fact:
    results: '{{ item }}'
  with_flattened:
  - '{{ logs.results }}'

- name: Pull lines out of results
  set_fact:
    lines: '{{ item }}'
  with_flattened:
  - '{{ results.stdout_lines }}'

- name: Download property files
  fetch:
    src: "{{ item }}"
    dest: '{{ conf_logs_dir }}'
  with_items:
  - "{{ lines }}"
  ignore_errors: yes
