---
# tasks file for opdk-setup-logs
- name: Find installation property files to download
  shell: "find {{ item.dir }} -type f -name '{{ item.name }}'"
  register: logs
  with_items:
  - { dir: '{{ apigee_installation_home }}/token/', name: '*properties' }
  - { dir: '{{ apigee_installation_home }}/*message-processor/', name: '*properties' }
  - { dir: '{{ apigee_installation_home }}/*router/', name: '*properties' }
  - { dir: '{{ apigee_installation_home }}/*postgresql/', name: '*properties' }
  - { dir: '{{ apigee_installation_home }}/*postgres-server/', name: '*properties' }
  - { dir: '{{ apigee_installation_home }}/*cassandra/', name: '*properties' }
  - { dir: '{{ apigee_installation_home }}/*qpid-server/', name: '*properties' }
  - { dir: '{{ apigee_installation_home }}/*qpidd/', name: '*properties' }
  - { dir: '{{ apigee_installation_home }}/*zookeeper/', name: '*properties' }
  ignore_errors: yes

- name: Pull results out of property search
  set_fact:
    results: '{{ item }}'
  with_flattened:
  - '{{ logs.results }}'

- name: Pull lines out of results
  set_fact:
    lines: '{{ item }}'
  with_flattened:
  - '{{ results.stdout_lines }}'

- name: Download property files
  fetch:
    src: "{{ item }}"
    dest: '{{ conf_logs_dir }}'
  with_items:
  - "{{ lines }}"
  ignore_errors: yes
