---
- hosts: '{{ hosts }}'
  become: yes
  vars:
    pubkey: '~/.ssh/id_rsa.pub'
  tasks:
  - name: Copy local public keys too server
    authorized_key:
      user: root
      state: present
      key: "{{ lookup('file', '{{ pubkey }}') }}"

  - name: Enable root login over SSH
    lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: '(^#)(PermitRootLogin yes)'
      line: '\2'
      backrefs: yes
    notify:
    - Restart SSH service

  handlers:
  - name: Restart SSH service
    service:
      name: sshd
      state: restarted
