---
- include: aws_facts.yml
  tags:
  - prep

- include: opdk-setup-os-admin-user.yml
  tags:
  - os

- hosts: dc-1
  strategy: free
  roles:
  - opdk-setup-openjdk
  tags:
  - openjdk

- include: opdk-setup-checkout-binaries.yml
  tags:
  - checkout

- include: opdk-setup-installation-apigee-user.yml

- include: opdk-setup-org.yml
  tags:
  - org

- hosts: dc-1
  strategy: free
  roles:
  - opdk-setup-apigee-config-files
  tags:
  - logs
