---
- hosts: "{{ hosts }}"
  strategy: free
  vars_files:
  - opdk-setup-settings.yml
  roles:
  - opdk-setup-bootstrap-rollback
  tags:
  - rollback-bootstrap
  - rollback

- hosts: "{{ hosts }}"
  strategy: free
  become: yes
  vars_files:
  - opdk-setup-settings.yml
  roles:
  - opdk-setup-os-common-rollback
  - opdk-setup-os-rollback
  tags:
  - os-rollback
  - rollback


