---
# tasks file for opdk-setup-collectd

- name: Collectd base dir exists
  stat:
    path: '{{ collectd_base_dir }}'
  register: cbase

- name: Collectd run dir exists
  stat:
    path: '{{ collectd_pid_file | dirname }}'
  register: crun

- name: Collectd plugin dir exists
  stat:
    path: '{{ collectd_plugin_dir }}'
  register: cplugin

- name: Collectd types dir exists
  stat:
    path: '{{ collectd_types_db_dir }}'
  register: cplugin

- name: is collectd installed?
  set_fact:
    installed_collectd: '{{ cbase.stat.exists and crun.stat.exists and cplugin.stat.exists and cplugin.stat.exists }}'

- name: Install collectd dependencies
  yum:
    name: '{{ item }}'
    state: present
  with_items:
  - '@Development Tools'
  - libcurl
  - libcurl-devel
  - rrdtool
  - rrdtool-devel
  - perl-devel
  - libgcrypt-devel
  - gcc
  - make
  - gcc-c++
  - yajl-devel
  - kernel-devel
  - automake
  - perl-ExtUtils-Embed
  - python-devel
  - python-psutil
  - man
  when: '{{ not installed_collectd }}'

- name: Clean up config files
  file:
    path: '{{ item }}'
    state: absent
  with_items:
  - '{{ collectd_conf_dir }}'
  - '{{ collectd_conf_file }}'

- name: Stop collectd if it's running
  shell: "kill -9 `cat {{ collectd_pid_file }}`"
  ignore_errors: yes

- name: Remove collectd pid
  file:
    path: '{{ collectd_pid_file }}'
    state: absent
  ignore_errors: yes

- name: Find python lib folder
  shell: "python -c 'from distutils.sysconfig import get_python_lib; print get_python_lib()'"
  register: python_lib_dir

- name: Create folders
  file:
    path: '{{ item.dir }}'
    state: '{{ item.state }}'
  with_items:
  - { dir: '{{ collectd_base_dir }}', state: 'directory' }
  - { dir: '{{ collectd_conf_dir }}', state: 'directory' }
  - { dir: '{{ collectd_plugin_dir }}', state: 'directory' }
  - { dir: '{{ collectd_types_db_dir }}', state: 'directory' }
  - { dir: '{{ collectd_src_parent_dir }}', state: 'directory' }

- name: Copy collectd python dir
  copy:
    src: collectd/python/
    dest: "{{ collectd_base_dir }}"

- name: Copy collectd ruby dir
  copy:
    src: collectd/ruby/
    dest: "{{ collectd_base_dir }}"

- name: Set ruby as executable
  file:
    state: file
    mode: 0755
    path: '{{ item }}'
  with_items:
  - '{{ collectd_base_dir }}/tcpconnstates.rb'

- name: Copy collectd share dir
  copy:
    src: collectd/share/
    dest: "{{ collectd_types_db_dir }}"

- name: Copy collectd java dir
  copy:
    src: collectd/java/
    dest: "{{ collectd_types_db_dir }}/java"

- name: Copy {{ collectd_pkg_name }}-{{ collectd_version }} source tarball
  ignore_errors: yes
  register: collectd_src_copy_status
  copy:
    src: '{{ collectd_src_filename }}'
    dest: '/tmp/'

- block:

  - name: Download {{ collectd_pkg_name }}-{{ collectd_version }} source tarball
    get_url:
      dest: '/tmp/'
      url: '{{ collectd_file_repository }}/{{ collectd_src_filename }}'
      sha256sum: '{{ collectd_file_sha_256 }}'

  - name: Copy downloaded {{ collectd_pkg_name }}-{{ collectd_version }} source tarball to local machine
    fetch:
      dest: '{{ collectd_src_filename }}'
      src: '/tmp/{{ collectd_src_filename }}'
      flat: yes

  when: collectd_src_copy_status | failed

- name: Copy collectd-generic-jmx rpm
  ignore_errors: yes
  register: collectd_generic_jmx_copy_status
  copy:
    src: '{{ item }}'
    dest: '/tmp/'
  with_items:
  - '{{ collectd_generic_jmx_filename }}'
  - '{{ collected_java_filename }}'

- debug: var=collectd_generic_jmx_copy_status

- block:

    - name: Download collected rpms
      get_url:
        dest: /tmp/
        url: '{{ item }}'
      with_items:
      - '{{ collectd_generic_jmx_url }}'
      - '{{ collectd_java_url }}'

    - name: Copy downloaded collected rpms to local machine
      fetch:
        dest: '{{ item }}'
        src: '/tmp/{{ item }}'
        flat: yes
      with_items:
      - '{{ collectd_generic_jmx_filename }}'
      - '{{ collected_java_filename }}'

  when:  collectd_generic_jmx_copy_status | failed

- name: Install collected_generic_jmx if this is for collected 5.5.0
  when: collectd_version == '5.5.0'
  yum:
    name: '{{ item }}'
    state: present
  with_items:
  - '/tmp/{{ collected_java_filename }}'
  - '/tmp/{{ collectd_generic_jmx_filename }}'

- pause:

- name: Unarchive {{ collectd_pkg_name }}-{{ collectd_version }} tarball
  unarchive:
    src: '/tmp/{{ collectd_src_filename }}'
    dest: '{{ collectd_src_parent_dir }}'
    copy: no
    creates: '{{ collectd_src_parent_dir }}/{{ collectd_pkg_name }}-{{ collectd_version }}'

- name: Configure {{ collectd_pkg_name }}-{{ collectd_version }} build
  shell: ./configure --prefix=/usr --with-java --with-python --with-librrd --enable-rrdtool --enable-aggregation --enable-debug --sysconfdir=/etc --localstatedir=/var --libdir=/usr/lib --mandir=/usr/share/man
  args:
    chdir: '{{ collectd_src_parent_dir }}/{{ collectd_pkg_name }}-{{ collectd_version }}'

- name: Make {{ collectd_pkg_name }}-{{ collectd_version }}
  shell: make all install
  args:
    chdir: '{{ collectd_src_parent_dir }}/{{ collectd_pkg_name }}-{{ collectd_version }}'

- name: Update dynamic collectd.d
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items:
  - { src: 'collectd.conf.j2', dest: '{{ collectd_conf_file }}' }
  - { src: 'collectd/collect.d/aggregation.conf.j2', dest: '{{ collectd_conf_dir }}/aggregation.conf' }
  - { src: 'collectd/collect.d/cassandra_memory.conf.j2', dest: '{{ collectd_conf_dir }}/cassandra_memory.conf' }
  - { src: 'collectd/collect.d/cassandra.conf.j2', dest: '{{ collectd_conf_dir }}/cassandra.conf' }
  - { src: 'collectd/collect.d/diskusage_percent.conf.j2', dest: '{{ collectd_conf_dir }}/diskusage_percent.conf' }
  - { src: 'collectd/collect.d/graphite.conf.j2', dest: '{{ collectd_conf_dir }}/graphite.conf' }
  - { src: 'collectd/collect.d/memory_load_stats.conf.j2', dest: '{{ collectd_conf_dir }}/memory_load_stats.conf' }
  - { src: 'collectd/collect.d/mp_application_stats.conf.j2', dest: '{{ collectd_conf_dir }}/mp_application_stats.conf' }
  - { src: 'collectd/collect.d/mp_traffic.conf.j2', dest: '{{ collectd_conf_dir }}/mp_traffic.conf' }
  - { src: 'collectd/collect.d/router_application_stats.conf.j2', dest: '{{ collectd_conf_dir }}/r_application_stats.conf' }
  - { src: 'collectd/collect.d/mp_connection_stats.conf.j2', dest: '{{ collectd_conf_dir }}/rmp_connection_stats.conf' }
  - { src: 'collectd/collect.d/mp_connection_tcp_stats.conf.j2', dest: '{{ collectd_conf_dir }}/rmp_connection_tcp_stats.conf' }
  - { src: 'collectd/collect.d/mp_http_stats.conf.j2', dest: '{{ collectd_conf_dir }}/rmp_http_stats.conf' }
  - { src: 'collectd/collect.d/mp_memory_stats.conf.j2', dest: '{{ collectd_conf_dir }}/rmp_memory_stats.conf' }
  - { src: 'collectd/collect.d/mp_thread_stats.conf.j2', dest: '{{ collectd_conf_dir }}/rmp_thread_stats.conf' }

- name: Update static collectd.d
  copy:
    src: collectd/conf/{{ item }}
    dest: '{{ collectd_conf_dir }}/{{ item }}'
  with_items:
  - df.conf

- name: Start collectd service
  shell: 'collectd -C {{ collectd_conf_file }}'
