---
# tasks file for opdk-shutdown
- name: Stop Apigee
  shell: '{{ all_stop }}'

- name: Remove left over pid files
  shell: 'find {{ apigee_pid_path }} -type f -name *.pid | xargs rm -rf {}'

- name: Remove any left over lock files
  shell:'rm -rf {{ apigee_lock_path }}/*'
