---
- hosts: dc-1
  strategy: free
  roles:
  - opdk-setup-selinux-disable
  - opdk-dns-resolver
  - opdk-shutdown-iptables
  - opdk-time-sync
  - opdk-setup-hostfile
  - opdk-setup-apigee-user
  - opdk-setup-os-common
  - opdk-setup-os-common-extra
  - opdk-setup-os-dev-validation

- hosts: ds
  serial: 1
  roles:
  - opdk-setup-os-ds

- hosts: ldap
  strategy: free
  roles:
  - opdk-setup-os-ldap

- hosts: rmp
  strategy: free
  roles:
  - opdk-setup-os-rmp

- hosts: qpid
  strategy: free
  roles:
  - opdk-setup-os-qpid

- hosts: pg
  strategy: free
  roles:
  - opdk-setup-os-postgres
