---
# tasks file for opdk-setup-system-config-logs

- name: Find system installation logs and configs to download
  shell: "find {{ item.dir }} -type f -name '{{ item.name }}'"
  register: logs
  with_items:
  - '{{ system_config_files }}'
  ignore_errors: yes

- name: Setup stdout_lines collection
  set_fact:
     lines: "{{ [0, 1] | map('extract', logs.results, 'stdout_lines') | list }}"

- name: Download files found
  fetch:
    src: "{{ item }}"
    dest: '{{ conf_logs_dir }}'
  with_items: "{{ lines }}"
