---

- hosts: planet
  become: true
  strategy: free
  roles:
  - opdk-setup-aws
  tags:
  - apigee
  - os
  - aws

- hosts: planet
  become: true
  strategy: free
  roles:
  - opdk-setup-selinux-disable
  - opdk-shutdown-iptables
  - opdk-time-sync
  - opdk-setup-hostfile
  - opdk-setup-os-minimum
  - opdk-setup-os-common
  tags:
  - os
  - os-basic

- hosts: planet
  become: true
  strategy: free
  roles:
  - opdk-setup-apigee-user
  tags:
  - apigee
  - os

#- hosts: ds
#  become: true
#  strategy: free
#  roles:
#  - opdk-setup-os-ds
#  tags:
#  - os
#  - os-ds

#- hosts: ldap
#  become: true
#  strategy: free
#  roles:
#  - opdk-setup-os-ldap
#  tags:
#  - os
#  - os-ldap

#- hosts: rmp
#  become: true
#  strategy: free
#  roles:
#  - opdk-setup-os-rmp
#  tags:
#  - os
#  - os-rmp

#- hosts: qpid
#  become: true
#  strategy: free
#  roles:
#  - opdk-setup-os-qpid
#  tags:
#  - os
#  - os-qpid

#- hosts: pg
#  become: true
#  strategy: free
#  roles:
#  - opdk-setup-os-postgres
#  tags:
#  - os
#  - os-pg

- hosts: planet
  become: true
  strategy: free
  roles:
  - opdk-setup-system-configs-logs
  tags:
  - os
  - os-logs
  - logs
