---
- include: facts.yml

- hosts: planet
  roles:
  - opdk-setup-apigee-log-files
  tags:
  - logs
  - apigee-logs

- hosts: planet
  become: true
  strategy: free
  roles:
  - opdk-setup-system-configs-logs
  tags:
  - os
  - os-logs
  - logs
