---
# Prime each target server with the correct setup
- include: facts.yml

- include: opdk-setup-os.yml

- include: opdk-setup-openjdk.yml
  vars:
    hosts: 'dc-1'

- include: opdk-setup-bootstrap.yml
  vars:
    hosts: 'dc-1'

- include: opdk-setup-component-installer.yml
  vars:
    hosts: 'dc-1'

- include: opdk-setup-ds.yml
  vars:
    hosts: 'dc-1-ds'

- include: opdk-setup-ms.yml
  vars:
    hosts: 'dc-1-ms'

- include: opdk-setup-rmp.yml
  vars:
    hosts: 'dc-1-rmp'

- include: opdk-setup-qpid.yml
  vars:
    hosts: 'dc-1-qpid'

- include: opdk-setup-postgres.yml
  vars:
    hosts: 'dc-1-pg'

- include: opdk-setup-startup.yml

- include: opdk-setup-validate.yml

- include: opdk-setup-org.yml

- include: opdk-setup-status.yml
  vars:
    hosts: 'dc-1'

- include: opdk-setup-config-files.yml

- include: opdk-setup-log-files.yml
