---
- include: facts.yml

- include: opdk-setup-os.yml

- include: opdk-setup-openjdk.yml
  vars:
    hosts: 'dc-2'

- include: opdk-setup-bootstrap.yml
  vars:
    hosts: 'dc-2'

- include: opdk-setup-component-installer.yml
  vars:
    hosts: 'planet'

- include: opdk-setup-ds.yml
  vars:
    hosts: 'dc-2-ds'

- include: opdk-setup-ds.yml
  vars:
    hosts: 'dc-1-ds'

- hosts: dc-1-ms
  roles:
  - opdk-cassandra-client-update

- include: opdk-setup-ms.yml
  vars:
    hosts: 'dc-1-ms'

- hosts: dc-2-ds
  vars:
    opdk_region: dc-1
  roles:
  - opdk-cassandra-rebuild
  tags:
  - rebuild

- include: opdk-setup-ms.yml
  vars:
    hosts: 'dc-2-ms'

- include: opdk-setup-rmp.yml
  vars:
    hosts: 'dc-2-rmp'

- include: opdk-setup-rmp.yml
  vars:
    hosts: 'dc-1-rmp'

- hosts: dc-2-qpid
  roles:
  - opdk-setup-qpid
  tags:
  - qpid

- include: opdk-setup-postgres.yml
  vars:
    hosts: 'dc-2-pg'

#- include: opdk-setup-postgres.yml
#  vars:
#    hosts: 'dc-1-pg'

- include: opdk-setup-startup.yml

- include: opdk-setup-validate.yml

- include: opdk-setup-org.yml

- include: opdk-setup-status.yml
  vars:
    hosts: 'dc-1'

- include: opdk-setup-config-files.yml

- include: opdk-setup-log-files.yml
