---
- hosts: planet
  gather_facts: yes
  vars_files:
  - opdk-setup-settings.yml
  roles:
  - opdk-setup-silent-installation-config
  tags:
  - silent-file
  - common

- hosts: planet
  gather_facts: yes
  vars_files:
  - opdk-setup-settings.yml
  roles:
  - opdk-setup-component-installer
  tags:
  - installer
  - common
