---
- hosts: pgmaster
  serial: 1
  roles:
  - opdk-setup-postgres
  - opdk-setup-postgres-master
  tags:
  - pg
  - pgmaster

- hosts: pgstandby
  serial: 1
  roles:
  - opdk-setup-postgres
  - opdk-setup-postgres-standby
  tags:
  - pg
  - pgstandby
