---
- hosts: ds
  serial: 1
  roles:
  - opdk-startup
  tags:
  - start-ds
  - startup

- hosts: ms
  serial: 1
  roles:
  - opdk-startup
  tags:
  - start-ms
  - startup

- hosts: rmp
  serial: 1
  roles:
  - opdk-startup
  tags:
  - start-rmp
  - startup

- hosts: sax
  serial: 1
  roles:
  - opdk-startup
  tags:
  - startup-sax
  - startup

