---
- hosts: '{{ hosts }}'
  tasks:
  - name: Determine OPDK region of this node
    set_fact:
      opdk_region: 'dc-1'
    when: "{{ inventory_hostname in groups['dc-1'] }}"
  - name: Determine OPDK region of this node
    set_fact:
      opdk_region: 'dc-2'
    when: "{{ inventory_hostname in groups['dc-2'] }}"
