---
- hosts: '{{ hosts }}'
  tasks:
  - name: Obtain status of selinux
    shell: /usr/sbin/sestatus
    register: status

  - debug: var=status

  - assert:
      that:
        - "'disabled' in status.stdout"