---

- include: 4150703-main.yml
  when: opdk_version | version_compare('4.16.01', '<')

- include: 4160100-main.yml
  when: opdk_version | version_compare('4.16.01', '>=')

- name: AIO Install Report
  debug:
    var: aio_install_results
