---
- name: Copy license file
  copy:
    src: "{{ opdk_license_file_name }}"
    dest: "{{ opdk_license_file_path }}"
    owner: '{{ opdk_user_name }}'
    group: '{{ opdk_group_name }}'
    mode: 0644
    force: yes

- include: 4150703-main.yml
  when: opdk_version | version_compare('4.15.07', '<=')

- name: Install Apigee Setup
  shell: 'bash {{ apigee_service }} apigee-setup install'
  when: opdk_version | version_compare('4.16', '>=')

- name: Install Apigee Validate
  shell: 'bash {{ apigee_service }} apigee-validate install'
  when: opdk_version | version_compare('4.16', '>=')

- name: Install Apigee adminapi
  shell: 'bash {{ apigee_service }} apigee-adminapi install'
  when: opdk_version | version_compare('4.16', '>=')
