---
- hosts: dc-1
  become: yes

  tasks:
  - name: Copy authorized_keys file from vagrant to apigee user
    copy:
      src: /home/vagrant/.ssh/authorized_keys
      dest: /home/apigee/.ssh/authorized_keys
      owner: apigee
      group: apigee
      mode: 0600
      remote_src: yes
