---
# tasks file for opdk-baas-onboarding
- name: Create Baas org and user
  shell: '{{ apigee_installation_home }}/baas-usergrid/bin/create_org_and_user.py -o {{ org_name }} -a {{ opdk_user_name }} -p {{ opdk_user_pass }}'
  register: result

- name: Bass org and user report
  debug:
    var: result
