---
# tasks file for aws-stop
- name: Load EC2 instance ids
  ec2_facts:

- name: Stop EC2 instance ids
  ec2:
    state: stopped
    instance_ids: '{{ ansible_ec2_instance_id }}'
    aws_access_key: '{{ aws_access_key }}'
    aws_secret_key: '{{ aws_secret_key }}'
    aws_region: '{{ aws_region }}'