---
- hosts: '{{ region }}-ds'
  serial: 1
  roles:
  - opdk-startup
  tags:
  - start-ds
  - startup

- hosts: '{{ region }}-ms'
  serial: 1
  roles:
  - opdk-startup
  tags:
  - start-ms
  - startup

- hosts: '{{ region }}-rmp'
  serial: 1
  roles:
  - opdk-startup
  tags:
  - start-rmp
  - startup

- hosts: '{{ region }}-qpid'
  serial: 1
  roles:
  - opdk-startup
  tags:
  - startup-qpid
  - startup

- hosts: '{{ region }}-pg'
  serial: 1
  roles:
  - opdk-startup
  tags:
  - startup-pg
  - startup

