---
- hosts: ds
  serial: 1
  roles:
  - opdk-restart
  tags:
  - restart-ds
  - restart

- hosts: ms
  serial: 1
  roles:
  - opdk-restart
  tags:
  - restart-ms
  - restart

- hosts: rmp
  serial: 1
  roles:
  - opdk-restart
  tags:
  - restart-rmp
  - restart

- hosts: qpid
  serial: 1
  roles:
  - opdk-restart
  tags:
  - restart-qpid
  - restart

- hosts: pg
  serial: 1
  roles:
  - opdk-restart
  tags:
  - restart-pg
  - restart
