---
- hosts: '{{ hosts }}'
  strategy: free
  roles:
  - opdk-setup-silent-installation-config
  tags:
  - silent
  - common

- hosts: '{{ hosts }}'
  strategy: free
  roles:
  - opdk-setup-component-installer
  tags:
  - installer
  - common
