---
# tasks file for opdk-setup-os-qpid
- name: Update limits.conf
  copy:
    src: apigee-qpid.limits.conf
    dest: /etc/security/limits.d/apigee-qpid.limits.conf
    owner: root
    group: root
    mode: 0644
