---
# tasks file for external-port-connectivity-validator-mp

- name: MP JMX connectivity status
  wait_for:
    port: '{{ mp_jmx_port }}'
    host: '{{ inventory_hostname}}'
    timeout: 1
  register: mp_jmx_port_status

- name: MP External Mgmt connectivity status
  wait_for:
    port: '{{ mp_ext_mgmt_port }}'
    host: '{{ inventory_hostname}}'
    timeout: 1
  register: mp_ext_mgmt_port_status

