---
# tasks file for opdk-setup-ms

- include: 4150703-main.yml
  when: opdk_version | version_compare('4.16.01', '<')

- name: Install Apigee Management Server
  shell: '{{ apigee_setup }} -p ms -f {{ opdk_response_file_path }}'
  when: opdk_version | version_compare('4.16.01', '>=')

