---
- include: opdk-setup-ds.yml

- include: opdk-cassandra-client-update.yml

- include: opdk-setup-ms.yml
  vars:
    hosts: dc-1-ms

- include: opdk-cassandra-rebuild.yml

- include: opdk-setup-ms.yml
  vars:
    hosts: dc-2-ms

- include: opdk-setup-rmp.yml
  vars:
    hosts: dc-2-ms

- include: opdk-setup-qpid.yml
  vars:
    hosts: dc-2-qpid

- include: opdk-setup-postgres.yml
  vars:
    hosts: dc-2-pgstandby

#- include: opdk-setup-sax.yml

- include: opdk-setup-startup.yml

- include: opdk-setup-status.yml
