---
- hosts: pgmaster
  serial: 1
  vars_files:
  - opdk-setup-settings.yml
  roles:
  - opdk-setup-postgres
  - opdk-setup-postgres-master
  tags:
  - pgmaster

- hosts: pgstandby
  serial: 1
  vars_files:
  - opdk-setup-settings.yml
  roles:
  - opdk-setup-postgres
  - opdk-setup-postgres-standby
  tags:
  - pgstandby
