---
- include: aws_facts.yml

- include: opdk-setup-os-admin-user.yml
  tags:
  - os

- include: opdk-setup-openjdk.yml

- include: opdk-setup-bootstrap.yml

- include: opdk-setup-create-archive.yml

- hosts: '{{ hosts }}'
  roles:
  - opdk-setup-download-archive
  tags:
  - download

