---
- hosts: dc1
  become: true
  strategy: free
  roles:
  - opdk-dns-resolver
  - opdk-shutdown-iptables
  - opdk-time-sync
  - opdk-setup-hostfile
  - opdk-setup-selinux
  - opdk-setup-os
  - opdk-setup-os-dev-validation
  - opdk-setup-installer