---
# tasks file for internal-port-connectivity-validator-baas-portal
- name: Baas Portal port connectivity status
  wait_for:
    port: '{{ baas_portal_port }}'
    host: '{{ local_address }}'
    timeout: 1
  register: baas_portal_port_status
  ignore_errors: yes
