---
- hosts: dc1
  become: true

  roles:
  - opdk-setup-selinux-disable
  - apigee-dns-resolver
  - apigee-shutdown-iptables
  - apigee-time-sync
  - opdk-setup-hostfile
  - opdk-setup-os
  - opdk-setup-os-dev-validation
  - opdk-setup-installer
  - opdk-setup-aio
  - opdk-setup-org
  - opdk-setup-collectd
  - opdk-setup-graphite
  - opdk-setup-grafana
  - opdk-setup-status
  - opdk-setup-logs-configs
