# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.ssh.insert_key = false
  # config.vm.box = "nrel/CentOS-6.5-x86_64"
  # config.vm.box = "nrel/CentOS-6.7-x86_64"
  config.vm.box = "centos/7"

  config.vm.define "a1n1" do |node|
    node.vm.hostname = "a1n1"
    node.vm.network "private_network", type: "dhcp"
    node.vm.network "forwarded_port", guest: 80, host: 9090
    node.vm.network "forwarded_port", guest: 1099, host: 1099
    node.vm.network "forwarded_port", guest: 1100, host: 1100
    node.vm.network "forwarded_port", guest: 1101, host: 1101
    node.vm.network "forwarded_port", guest: 1102, host: 1102
    node.vm.network "forwarded_port", guest: 1103, host: 1103
    node.vm.network "forwarded_port", guest: 2181, host: 2181
    node.vm.network "forwarded_port", guest: 3000, host: 3000
    node.vm.network "forwarded_port", guest: 3306, host: 3306
    node.vm.network "forwarded_port", guest: 7199, host: 7199
    node.vm.network "forwarded_port", guest: 8080, host: 8080
    node.vm.network "forwarded_port", guest: 8081, host: 8081
    node.vm.network "forwarded_port", guest: 8082, host: 8082
    node.vm.network "forwarded_port", guest: 8083, host: 8083
    node.vm.network "forwarded_port", guest: 8084, host: 8084
    node.vm.network "forwarded_port", guest: 9000, host: 9000
    node.vm.network "forwarded_port", guest: 9001, host: 9001
  end

  config.vm.provider :virtualbox do |vb|
    vb.memory = 4096
  end

  config.vm.provision :ansible do |ansible|
    ansible.playbook = "opdk-setup-aio.yml"
    ansible.verbose = "vv"
    ansible.inventory_path = 'aio-inventory'
    ansible.extra_vars = {hosts: "dc1"}
  end

end
