---
- include: facts.yml

- include: aws_terminate.yml
  vars:
    hosts: planet

- include: aws_create.yml
  vars:
    node_count: 5
    session_name: 1601-ol67-installation-1

- hosts: planet
  gather_facts: no
  serial: 1

  tasks:
  - wait_for:
      host: '{{ inventory_hostname }}'
      port: 22
