---
# tasks file for opdk-setup-jdk
- include: jdk17-main.yml
  when: jdk_version == '1.7'

- include: jdk18-main.yml
  when: jdk_version == '1.8'

- name: Update JAVA_HOME with Open Jdk
  lineinfile:
    dest: /etc/environment
    regexp: "^export JAVA_HOME"
    line: 'export JAVA_HOME={{ open_jdk_path }}'
    backup: yes
  register: environ_status

- name: Update JAVA_HOME with Open Jdk
  debug:
    var: environ_status

