---
# Prime each target server with the correct setup
- hosts: dc1
  become: true
  strategy: free
  roles:
  - opdk-setup-selinux-disable
  - opdk-dns-resolver
  - opdk-shutdown-iptables
  - opdk-time-sync
  - opdk-setup-hostfile
  - opdk-setup-os
  - opdk-setup-os-dev-validation
  - opdk-setup-installer

- hosts: ds
  become: true
  serial: 1
  roles:
  - opdk-setup-ds

- hosts: ms
  become: true
  strategy: free
  roles:
  - opdk-setup-ms
  - opdk-setup-org

- hosts: rmp
  become: true
  strategy: free
  roles:
  - opdk-setup-rmp

- hosts: pgmaster
  become: true
  vars:
    target_host_name: "{{ hostvars[ansible_hostname]['groups']['pgstandby'][0] }}"
  roles:
  - opdk-setup-ssh

- hosts: pgstandby
  become: true
  vars:
    target_host_name: "{{ hostvars[ansible_hostname]['groups']['pgmaster'][0] }}"
  roles:
  - opdk-setup-ssh

- hosts: sax
  become: true
  roles:
  - opdk-setup-sax

- hosts: sax
  become: true
  roles:
  - opdk-setup-sax-replication
