# -*- mode: ruby -*-
# vi: set ft=ruby :

ms_jmx_port = 1099
router_jmx_port = 1100
mp_jmx_port = 1101
ingest_jmx_port = 1102
pgserver_jmx_port = 1103
pg_db_port = 5432
zk_jmx_port = 2181
cassandra_jmx_port = 7199
ms_http_port = 8080
router_self_port = 8081
mp_self_port = 8082
qpid_self_port = 8083
pgserver_self_port = 8084
cassandra_db_port = 9160
ui_http_port = 9000
edge_proxy_port = 9001
mysql_port = 3306
open_ldap_port = 10389
graphite_http_port = 80
grafana_http_port = 3000

Vagrant.configure(2) do |config|
  config.ssh.insert_key = false
  # config.vm.box = "nrel/CentOS-6.5-x86_64"
  # config.vm.box = "nrel/CentOS-6.7-x86_64"
  config.vm.box = "centos/7"

  config.vm.define "a5n1" do |node|
    node.vm.hostname = "a5n1"
    # node.vm.network "private_network", type: "dhcp"
    node.vm.network "private_network", ip: "172.28.128.5"
    node.vm.network "forwarded_port", guest: ms_http_port, host: ms_http_port
    node.vm.network "forwarded_port", guest: ms_jmx_port, host: ms_jmx_port
    node.vm.network "forwarded_port", guest: grafana_http_port, host: grafana_http_port
    node.vm.network "forwarded_port", guest: cassandra_jmx_port, host: cassandra_jmx_port
    node.vm.network "forwarded_port", guest: cassandra_db_port, host: cassandra_db_port
    node.vm.network "forwarded_port", guest: zk_jmx_port, host: zk_jmx_port
    node.vm.network "forwarded_port", guest: ui_http_port, host: ui_http_port
    node.vm.network "forwarded_port", guest: edge_proxy_port, host: edge_proxy_port
    node.vm.network "forwarded_port", guest: open_ldap_port, host: open_ldap_port
    node.vm.provider :virtualbox do |vb|
      vb.memory = 1024
    end
  end

  config.vm.define "a5n2" do |node|
    node.vm.hostname = "a5n2"
    # node.vm.network "private_network", type: "dhcp"
    node.vm.network "private_network", ip: "172.28.128.6"
    node.vm.network "forwarded_port", guest: router_jmx_port, host: router_jmx_port
    node.vm.network "forwarded_port", guest: router_self_port, host: router_self_port
    node.vm.network "forwarded_port", guest: mp_jmx_port, host: mp_jmx_port
    node.vm.network "forwarded_port", guest: mp_self_port, host: mp_self_port
    node.vm.provider :virtualbox do |vb|
      vb.memory = 1024
    end
  end

  config.vm.define "a5n3" do |node|
    node.vm.hostname = "a5n3"
    # node.vm.network "private_network", type: "dhcp"
    node.vm.network "private_network", ip: "172.28.128.7"
    node.vm.network "forwarded_port", guest: graphite_http_port, host: 9090
    node.vm.provider :virtualbox do |vb|
      vb.memory = 1024
    end
  end

  config.vm.define "a5n4" do |node|
    node.vm.hostname = "a5n4"
    # node.vm.network "private_network", type: "dhcp"
    node.vm.network "private_network", ip: "172.28.128.8"
    node.vm.network "forwarded_port", guest: qpid_self_port, host: qpid_self_port
    node.vm.network "forwarded_port", guest: pgserver_self_port, host: pgserver_self_port
    node.vm.network "forwarded_port", guest: pg_db_port, host: pg_db_port
    node.vm.network "forwarded_port", guest: pgserver_jmx_port, host: pgserver_jmx_port
    node.vm.network "forwarded_port", guest: ingest_jmx_port, host: ingest_jmx_port
    node.vm.provider :virtualbox do |vb|
      vb.memory = 1024
    end
  end

  config.vm.define "a5n5" do |node|
    node.vm.hostname = "a5n5"
    # node.vm.network "private_network", type: "dhcp"
    node.vm.network "private_network", ip: "172.28.128.9"
    node.vm.provider :virtualbox do |vb|
      vb.memory = 1024
    end
  end


end
