---
- include: ../prep_os/facts.yml

- hosts: "{{ hosts }}"
  strategy: free
  become: yes
  roles:
  - opdk-setup-os-rollback


- hosts: "{{ hosts }}"
  strategy: free
  become: yes
  roles:
  - restart-node

