---
- hosts: "{{ hosts }}"
  become: true
  vars_files:
  - opdk-setup-settings.yml
  roles:
  - opdk-setup-installer-rollback

- hosts: "{{ hosts }}"
  become: true
  roles:
  - opdk-setup-installer-rollback
