---
- hosts: dc-1
  become_user: apigee

  tasks:
  - name: Create .ssh folder
    file:
      path: /home/apigee/.ssh/
      state: directory

  - name: Get authorized_keys
    copy:
      src: /home/mpurwar/.ssh/authorized_keys
      dest: /home/apigee/.ssh/authorized_keys