---
- hosts: rmp
  become: true
  serial: 1

  vars:
    local_repo_dir: ''

  tasks:
  - name: Stop the router and message processor node
    shell: '/opt/apigee/apigee-service/bin/apigee-all stop'
    
  - name: Expire the yum cache
    shell: 'yum clean expire-cache'
    register: yum_expire_cache_report

  - name: Clear the yum cache
    shell: 'yum clean all'
    register: yum_clean_status

  - name: Update the bootstrap and skip installing Java
    shell: 'bash {{ local_repo_dir }}/bootstrap.sh apigeeprotocol="file://" apigeerepobasepath={{ local_repo_dir }} JAVA_FIX=C'

  - name: Remove the existing message processor
    shell: 'yum -y erase edge-message-processor'

  - name: Install the updated message processor
    shell: 'yum -y install edge-message-processor'

  - name: Remove the existing edge router
    shell: 'yum -y erase edge-router'

  - name: Install the updated edge router
    shell: 'yum -y install edge-router'

  - name: Remove existing edge gateway
    shell: 'yum -y erase edge-gateway'

  - name: Install the updated edge gateway
    shell: 'yum -y install edge-gateway'

  - name: Configure all of the Apigee components
    shell: '/opt/apigee/apigee-service/bin/apigee-all configure'

  - name: Restart all Apigee components
    shell: '/opt/apigee/apigee-service/bin/apigee-all start'

