---
- hosts: dc-1
  strategy: free
  vars_files:
  - opdk-setup-settings.yml
  roles:
  - opdk-setup-selinux-disable
  - opdk-shutdown-iptables
  - opdk-time-sync
  - opdk-setup-hostfile
  - opdk-setup-os-common
  - opdk-setup-os-common-extra
  - opdk-setup-os-dev-validation
  tags:
  - os

- hosts: planet
  become: true
  strategy: free
  vars_files:
  - opdk-setup-settings.yml
  roles:
  - opdk-setup-apigee-user
  tags:
  - apigee