---
- hosts: localhost
  connection: local

  vars:
#    training_ami_id: ops-training-base-4.15.07-hvm (ami-15de907f)
#    oraclelinux_id: 'ami-cac986a0'
    oraclelinux_id: 'ami-e9c98683'
    image_id: '{{ oraclelinux_id }}'
#    instance_type: 'm3.large'
#    instance_type: 't2.medium'
    instance_type: 't2.medium'
#    instance_type: 't2.small'
    aws_access_key: '{{ aws_access_key_id }}'
    aws_secret_key: '{{ aws_secret_access_key }}'
    aws_region: 'us-east-1'
    key_name: cfrias
    security_group: OPDK
    name: newtest
    vpc_subnet_id: subnet-3fbcb64b
  tasks:

  - name: Provision an oracle linux 6.7 ami instance
    ec2:
      assign_public_ip: yes
      image: "{{ image_id }}"
      instance_type: '{{ instance_type }}'
      aws_access_key: '{{ aws_access_key }}'
      aws_secret_key: '{{ aws_secret_key }}'
      aws_region: '{{ aws_region }}'
      key_name: '{{ key_name }}'
      wait: yes
      state: present
      group: '{{ security_group }}'
      vpc_subnet_id: '{{ vpc_subnet_id }}'
      instance_tags:
        Name: cfrias-{{ session_name }}-n{{ item }}
        application: edge
        bag: infrastructure
        department: 45
        environment: training
        owner_contact_info: cfrias@apigeee.com
        pod: NA
        team_contact_info: cs-technical@apigee.com
        env: cfrias-sessions
    register: ec2
    with_sequence: count={{ node_count }}

  - name: OL 6.7 AMI provisioning Report
    debug:
      var: ec2

