---
- name: Check for ingest JMX port
  register: ingest_jmx_port_status
  ignore_errors: true
  wait_for:
    host: '{{ ansible_hostname }}'
    port: '{{ ingest_jmx_port }}'
    timeout: 1

- name: Check for postgres DB port
  register: pg_db_port_status
  ignore_errors: true
  wait_for:
    host: '{{ ansible_hostname }}'
    port: '{{ pg_db_port }}'
    timeout: 1

- name: Check for qpid HTTP port
  register: qpid_self_port_status
  ignore_errors: true
  wait_for:
    host: '{{ ansible_hostname }}'
    port: '{{ qpid_self_port }}'
    timeout: 1

- name: Setup Qpid and Postgres
  shell: "{{ apigee_installation_home }}/share/installer/apigee-setup.sh -f {{ opdk_response_file_path }} -p sax"
  ignore_errors: yes
  when: ingest_jmx_port_status | failed or pg_db_port_status | failed or qpid_self_port_status | failed

- name: Confirm ingest JMX port
  ignore_errors: true
  wait_for:
    timeout: 1
    host: '{{ ansible_hostname }}'
    port: '{{ ingest_jmx_port }}'
  register: ingest_jmx_port_status

- name: Confirm postgres DB port
  ignore_errors: true
  wait_for:
    timeout: 1
    host: '{{ ansible_hostname }}'
    port: '{{ pg_db_port }}'
  register: pg_db_port_status

- name: Confirm qpid HTTP port
  ignore_errors: true
  wait_for:
    timeout: 1
    host: '{{ ansible_hostname }}'
    port: '{{ qpid_self_port }}'
  register: qpid_self_port_status

- name: Ingest JMX port startup failed
  fail:
    msg: "Ingest JMX port failed to start"
  when: not ingest_jmx_port_status.state == 'started'

- name: Postgres DB port startup failed
  fail:
    msg: "Postgres DB port failed to start"
  when: not pg_db_port_status.state == 'started'

- name: Qpid HTTP port startup failed
  fail:
    msg: "Qpid HTTP port failed to start"
  when: not qpid_self_port_status.state == 'started'
