---
- name: Fix permissions on pgdata folder
  file:
    path: '{{ apigee_posgresql_data_dir }}'
    owner: '{{ opdk_user_name }}'
    group: '{{ opdk_group_name }}'
    mode: 0700
    state: directory

- name: Sax installation
  shell: '{{ apigee_setup_16 }} -p sax -f {{ opdk_response_file_path }}'

