---
# tasks file for opdk-setup-sax

- include: 4150703-main.yml
  when: opdk_version | version_compare('4.16.01', '<')

- name: Fix permissions on pgdata folder
  file:
    path: '{{ apigee_posgresql_data_dir }}'
    owner: '{{ opdk_user_name }}'
    group: '{{ opdk_group_name }}'
    mode: 0700
    state: directory
  when: opdk_version | version_compare('4.16.01', '>=')

- name: Sax installation
  shell: '{{ apigee_setup }} -p sax -f {{ opdk_installation_config_file }}'
  when: opdk_version | version_compare('4.16.01', '>=') and opdk_version | version_compare('4.16.05', '<')

- name: Sax installation
  shell: '{{ apigee_setup }} -p sax -f {{ opdk_installation_config_file }}'
  register: sax_install_results
  when: opdk_version | version_compare('4.16.05', '>=')
