---

- hosts: planet
  gather_facts: yes
  vars:
    public_ip_field_name: 'public_address'
    private_ip_field_name: 'local_address'
  pre_tasks:
  - setup:

  roles:
  - opdk-setup-default-settings
  - opdk-setup-silent-installation-config
  tags:
  - silent-file
  - common

- hosts: planet
  gather_facts: yes
  roles:
  - opdk-setup-component-installer
  tags:
  - installer
  - common
