---
- include: aws_facts.yml
  tags:
  - aws
  - common

- include: opdk-setup-os.yml
  tags:
  - os
  - common

- hosts: dc-1
  strategy: free
  roles:
  - opdk-setup-openjdk
  tags:
  - openjdk
  - common

- include: opdk-setup-bootstrap.yml

- include: opdk-setup-installer.yml

- include: opdk-setup-aio.yml

- include: opdk-setup-validate.yml

- include: opdk-setup-validate-cleanup.yml

- include: opdk-setup-org.yml

- hosts: dc-1
  strategy: free
  roles:
  - opdk-setup-apigee-config-files
  tags:
  - logs
