---

- hosts: planet
  gather_facts: yes
  pre_tasks:
  - setup:

  roles:
  - opdk-setup-default-settings
  - opdk-setup-silent-installation-config
  tags:
  - silent-file
  - common

- hosts: planet
  gather_facts: yes
  roles:
  - opdk-setup-component-installer
  tags:
  - installer
  - common
