---
- hosts: planet
  become: true
  roles:
  - opdk-setup-selinux-disable
  - opdk-shutdown-iptables
  - opdk-time-sync
  - opdk-setup-os-common
  - opdk-setup-os-minimum
  - opdk-setup-os-dev-validation
  - opdk-setup-apigee-user
  - opdk-setup-os-ds
  - opdk-setup-os-rmp
  - opdk-setup-os-qpid
  - opdk-setup-os-postgres
  tags:
  - common
  - os
