---
# tasks file for opdk-setup-ps
- include: common_integrated_facts.yml

- include: aws_integrated_facts.yml

- include: 4150703-main.yml
  when: opdk_version | version_compare('4.16.01', '<')

- name: Set permissions on pgdata folder
  file:
    path: '{{ apigee_posgresql_data_dir }}'
    owner: '{{ opdk_user_name }}'
    group: '{{ opdk_group_name }}'
    mode: 0700
    state: directory
  when: opdk_version | version_compare('4.16.01', '>=')

- name: Postgresql Server installation
  shell: '{{ apigee_setup }} -p ps -f {{ opdk_response_file_path }}'
  when: opdk_version | version_compare('4.16.01', '>=')
