---
- include: opdk-setup-ds.yml

- include: opdk-setup-ms.yml

- include: opdk-setup-rmp.yml

- include: opdk-setup-postgres.yml

- include: opdk-setup-startup.yml

- include: opdk-setup-validate.yml

- include: opdk-setup-org.yml

- include: opdk-setup-status.yml

