---
apigee_installation_path_prefix: /opt
apigee_installation_dir: apigee
apigee_installation_home: "{{ apigee_installation_path_prefix }}/{{ apigee_installation_dir }}"
apigee_service: '{{ apigee_installation_home }}/apigee-service/bin/apigee-service'
apigee_migrate: '{{ apigee_installation_home }}/apigee-migrate/bin/migrate.sh'

opdk_version: '4.16.01'

opdk_license_file_name: ~/.apigee/license.txt

admin_user: opdk@apigee.com
admin_pass: Apigee123!
new_user: y
user_name: opdk@apigee.com
user_pass: Apigee123!
first_name: Opdk
last_name: User
org_name: opdk
virtual_host_port: 9001
virtual_host_name: default
virtual_host_alias: '127.0.0.1'
env_name: test
ms_http_port: 8080
ax_group: axgroup001
