---
# tasks file for opdk-setup-os-common-extra
- block:
  - name: Update yum os packages
    yum:
      name: "{{ item }}"
      state: latest
    with_items:
    - bind-utils
    - chkconfig
    - curl
    - sudo
    - tar
    - wget
    - yum-utils
    - grep
    - rpm
    - sed
    - sudo
    - unzip
    - rsync
    - which
    - lsof
    - nc
    - dos2unix
    - tcpdump
    - tree
    - telnet
    - vim
    - openssh-clients
    - openssh-server
    - libselinux-python

  rescue:
    - name: Remove the typical qpid packages that cause yum failures
      shell: 'rpm -e $(rpm -qa | egrep "(qpid-|python-qpid|libqpid)")'

    - name: Retry to update yum os packages
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
      - bind-utils
      - chkconfig
      - curl
      - sudo
      - tar
      - wget
      - yum-utils
      - grep
      - rpm
      - sed
      - sudo
      - unzip
      - rsync
      - which
      - lsof
      - nc
      - dos2unix
      - tcpdump
      - tree
      - telnet
      - vim
      - openssh-clients
      - openssh-server
      - libselinux-python
