---
# Prime each target server with the correct setup
- include: aws_facts.yml
  tags:
  - aws
  - common

- include: opdk-setup-os.yml
  tags:
  - os

- include: opdk-setup-openjdk.yml
  tags:
  - openjdk
  - common

- include: opdk-setup-bootstrap.yml

- include: opdk-setup-openjdk.yml
  tags:
  - openjdk2
  - common

- include: opdk-setup-installer.yml

- include: opdk-setup-installation.yml

