---
- hosts: pgstandby
  vars_files:
  - opdk-setup-settings.yml
  roles:
  - opdk-setup-postgres
  tags:
  - pgstandby

- hosts: pgmaster
  vars_files:
  - opdk-setup-settings.yml
  roles:
  - opdk-setup-postgres-master
  tags:
  - pgmaster

- hosts: pgstandby
  vars_files:
  - opdk-setup-settings.yml
  roles:
  - opdk-setup-postgres-standby
  tags:
  - pgstandby

