---

#- include: opdk-setup-ssh.yml
#  tags:
#  - ssh

- include: opdk-postgres-deregistration.yml
  tags:
  - deregistration

#- include: opdk-setup-full-rollback.yml
#  vars:
#    hosts: dc-1-pgstandby
#  tags:
#  - pgstandby-rollback

#- include: opdk-setup-ssh.yml
#  tags:
#  - ssh

- hosts: pg
  serial: 1
  vars_files:
  - opdk-setup-settings.yml
  roles:
  - opdk-setup-sax
  tags:
  - sax

- include: opdk-setup-full-rollback.yml
  vars:
    hosts: dc-1-pgstandby
  tags:
  - pgstandby-rollback
