---
- hosts: '{{ hosts }}'
  become: yes
  gather_facts: no

  vars:
    pubkey: '~/.ssh/id_rsa.pub'
  tasks:
  - name: Wait for port 22
    wait_for:
      port: 22
      timeout: 300

  - name: Collect EC2 facts
    ec2_facts:

  - name: Collect general setup facts
    setup:

  - name: Copy local public keys too server
    authorized_key:
      user: root
      state: present
      key: "{{ lookup('file', '{{ pubkey }}') }}"

  - name: Enable root login over SSH
    lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: '(^#)(PermitRootLogin yes)'
      line: '\2'
      backrefs: yes
    notify:
    - Restart SSH service

  handlers:
  - name: Restart SSH service
    service:
      name: sshd
      state: restarted
